### ISSUE TITLE
Can't run multiple EE on same cluster

### ISSUE THREAD

**Issue by robotrapta** [groundlight/edge-endpoint#120]
I'd expect that I can run the EE twice in different namespaces on the same cluster.  But when I try that, I get this error in the `edge-endpoint` pod:

```
  Warning  FailedScheduling  3m5s  default-scheduler  0/1 nodes are available: pod has unbound immediate PersistentVolumeClaims. preemption: 0/1 nodes are available: 1 Preemption is not helpful for scheduling.
```

**Comment by robotrapta** [comment]
Manual workaround is to create a second PV and PVC like this:

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: edge-endpoint-pv2
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-sc
  hostPath:
    path: /opt/groundlight/edge2
```
